### ISSUE TITLE
metaphlanToPhyloseq error

### ISSUE THREAD

**Issue by mghanbari** [waldronlab/presentations#1]
Hi

When I want to use the script `metaphlanToPhyloseq`  I receive this error 

```
Error in strsplit(xnames, split = split, fixed = TRUE) : 
  non-character argument
Called from: strsplit(xnames, split = split, fixed = TRUE)
```

my data are the output from MetaPhlAn2.  Any idea what is the problem?

**Comment by mghanbari** [comment]
Well, I solved the problem. It was due to the nature of the data that were not in matrix form.

**Comment by lwaldron** [comment]
@mghanbari I'm sorry your issue escaped my attention! I've added a new filter to my GitHub notifications to make sure I don't miss them again.
